# Generated by Django 3.2.4 on 2021-06-10 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('fathersname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('classopted', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(5)])),
                ('marks', models.IntegerField()),
                ('dateenrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
